In [4]:
import numpy as np
import time

In [7]:
a =[ 1,2,3,4,5,6,7,8,5,6,7,4,3,56,7,5,3,3,5] * 10000000

start = time.time()
for i in range(len(a)):
    a[i] = a[i]*2

print("time taken ", time.time()-start)    

time taken  52.46652936935425


In [6]:
print("Hello")
for i in range(5):
    print(i)

Hello
0
1
2
3
4


In [8]:
b =np.array(a)
start = time.time()
new_b = b*2
print("time for numpy ", time.time()-start)


time for numpy  12.931746006011963


In [10]:
import sys
a = [1,2,3,4,5]
arr =np.array(a)

print("list size :",sys.getsizeof(a))
print("numpy size : ", arr.nbytes)





list size : 104
numpy size :  40


creation array

scalar  -> o dimension
[1 ,2 ,3 ,4] -> 1 dimension
[[123],[456]] -> 2 dimension

In [12]:
arr = [1,2,3,4,5]
arr = np.array(arr)
print(arr.ndim)

1


In [13]:
a =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)


2


In [14]:
a = np.array([[[1,2,34,],[4,5,6],[7,8,9]],[[1,2,34,],[4,5,6],[7,8,9]],[[1,2,34,],[4,5,6],[7,8,9]]])
print(a.ndim)

3


create list using inbuilt
np.arange(start,stop,stepsize)

In [16]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


crete evenly space array
np.linspace(start,stop,width_betwen_start_and_stop)

In [17]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


logorithimic scale array
np.logspace(start , end -> powers , no_of_values)

In [ ]:
arr =np.logspace(1,3,3)// from 10^1 to 10^3 with 3 numbers
print(arr)

[  10.  100. 1000.]


array full of zeros
np.zeros(array_size)

In [20]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


create matrix of zeros
np.zeros([rows,columns])


In [22]:
arr = np.zeros([3,5])
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


create array with all ones
np.ones(size_of_array) by default it is float
np.ones(size_of_array , dtype = int)

In [24]:
arr = np.ones(5)
print(arr)
arr = np.ones([3,5],dtype = int)
print(arr)


[1. 1. 1. 1. 1.]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


create array full of our choice
array with same elements 
np.full([row,column],defaultvalue)

In [26]:
arr = np.full(10,2)
print(arr)
arr = np.full([4,5],18)
print(arr)


[2 2 2 2 2 2 2 2 2 2]
[[18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]]


create uninitilase numpy array
np.empty(dimension)

In [30]:
x = np.empty([5,6])
print(x)

[[1.51842581e-311 1.02765654e-321 0.00000000e+000 0.00000000e+000
  7.56571287e-307 5.02034658e+175]
 [2.23238864e+180 7.55921240e-067 6.10346388e+170 5.44208862e-062
  2.76751198e-057 5.50976285e-144]
 [3.59751658e+252 3.96046095e+246 1.04918621e-153 7.69165785e+218
  5.04621343e+180 1.04917822e-153]
 [9.08366793e+223 2.23238864e+180 7.55921240e-067 6.10346388e+170
  5.44208862e-062 1.04915260e-153]
 [1.94918966e-153 3.93231563e-062 2.26301105e-076 3.69845030e-057
  2.59027896e-144 7.79952704e-143]]


generate random numbers array by default it is float
np.random.rand(size)

to create random matrix no need of square brasis 
np.random.rand(rows,column)

In [33]:
arr = np.random.rand(10)
print(arr)
arr = np.random.rand(3,4)
print(arr)

[0.50249277 0.28721389 0.11973345 0.94175198 0.09093709 0.27313931
 0.04169135 0.95523139 0.13760525 0.61356703]
[[0.89370944 0.69847307 0.02552313 0.40986251]
 [0.98561062 0.27381465 0.98121835 0.59692899]
 [0.23396101 0.12150604 0.86853966 0.50646272]]


standard normalization mean = 0 , standard deviation = 1
generate random numbers with mean =0 and std deviation = 1
np.random.randn(size)
np.random.randn(rows,column)

In [35]:
arr = np.random.randn(10)
print(arr.mean())

0.016856362014772662


In [38]:
arr = np.random.randn(3,4)
print(arr)
print(arr.mean())
print(arr.std())

[[ 0.40888953  0.73965366  0.30153221  1.00599111]
 [ 0.03886223  0.39444576 -0.20586043  1.19964818]
 [-0.02717395  2.08692062 -0.25547139 -0.84654087]]
0.40340805557089054
0.7439123179408663


random integer array with particular range 
np.random.randint(start,end,no_of_values)

In [ ]:
import numpy as np

c = np.random.randint(6,100,1)
print(c)

[29]
