In [4]:
import numpy as np
import time

In [7]:
a =[ 1,2,3,4,5,6,7,8,5,6,7,4,3,56,7,5,3,3,5] * 10000000

start = time.time()
for i in range(len(a)):
    a[i] = a[i]*2

print("time taken ", time.time()-start)    

time taken  52.46652936935425


In [6]:
print("Hello")
for i in range(5):
    print(i)

Hello
0
1
2
3
4


In [8]:
b =np.array(a)
start = time.time()
new_b = b*2
print("time for numpy ", time.time()-start)


time for numpy  12.931746006011963


In [10]:
import sys
a = [1,2,3,4,5]
arr =np.array(a)

print("list size :",sys.getsizeof(a))
print("numpy size : ", arr.nbytes)





list size : 104
numpy size :  40


creation array

scalar  -> o dimension
[1 ,2 ,3 ,4] -> 1 dimension
[[123],[456]] -> 2 dimension

In [12]:
arr = [1,2,3,4,5]
arr = np.array(arr)
print(arr.ndim)

1


In [13]:
a =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)


2


In [14]:
a = np.array([[[1,2,34,],[4,5,6],[7,8,9]],[[1,2,34,],[4,5,6],[7,8,9]],[[1,2,34,],[4,5,6],[7,8,9]]])
print(a.ndim)

3


create list using inbuilt
np.arange(start,stop,stepsize)

In [16]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


crete evenly space array
np.linspace(start,stop,width_betwen_start_and_stop)

In [17]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


logorithimic scale array
np.logspace(start , end -> powers , no_of_values)

In [ ]:
arr =np.logspace(1,3,3)// from 10^1 to 10^3 with 3 numbers
print(arr)

[  10.  100. 1000.]


array full of zeros
np.zeros(array_size)

In [20]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


create matrix of zeros
np.zeros([rows,columns])


In [22]:
arr = np.zeros([3,5])
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


create array with all ones
np.ones(size_of_array) by default it is float
np.ones(size_of_array , dtype = int)

In [24]:
arr = np.ones(5)
print(arr)
arr = np.ones([3,5],dtype = int)
print(arr)


[1. 1. 1. 1. 1.]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


create array full of our choice
array with same elements 
np.full([row,column],defaultvalue)

In [26]:
arr = np.full(10,2)
print(arr)
arr = np.full([4,5],18)
print(arr)


[2 2 2 2 2 2 2 2 2 2]
[[18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]]


create uninitilase numpy array
np.empty(dimension)

In [30]:
x = np.empty([5,6])
print(x)

[[1.51842581e-311 1.02765654e-321 0.00000000e+000 0.00000000e+000
  7.56571287e-307 5.02034658e+175]
 [2.23238864e+180 7.55921240e-067 6.10346388e+170 5.44208862e-062
  2.76751198e-057 5.50976285e-144]
 [3.59751658e+252 3.96046095e+246 1.04918621e-153 7.69165785e+218
  5.04621343e+180 1.04917822e-153]
 [9.08366793e+223 2.23238864e+180 7.55921240e-067 6.10346388e+170
  5.44208862e-062 1.04915260e-153]
 [1.94918966e-153 3.93231563e-062 2.26301105e-076 3.69845030e-057
  2.59027896e-144 7.79952704e-143]]


generate random numbers array by default it is float
np.random.rand(size)

to create random matrix no need of square brasis 
np.random.rand(rows,column)

In [33]:
arr = np.random.rand(10)
print(arr)
arr = np.random.rand(3,4)
print(arr)

[0.50249277 0.28721389 0.11973345 0.94175198 0.09093709 0.27313931
 0.04169135 0.95523139 0.13760525 0.61356703]
[[0.89370944 0.69847307 0.02552313 0.40986251]
 [0.98561062 0.27381465 0.98121835 0.59692899]
 [0.23396101 0.12150604 0.86853966 0.50646272]]


standard normalization mean = 0 , standard deviation = 1
generate random numbers with mean =0 and std deviation = 1
np.random.randn(size)
np.random.randn(rows,column)

In [35]:
arr = np.random.randn(10)
print(arr.mean())

0.016856362014772662


In [38]:
arr = np.random.randn(3,4)
print(arr)
print(arr.mean())
print(arr.std())

[[ 0.40888953  0.73965366  0.30153221  1.00599111]
 [ 0.03886223  0.39444576 -0.20586043  1.19964818]
 [-0.02717395  2.08692062 -0.25547139 -0.84654087]]
0.40340805557089054
0.7439123179408663


random integer array with particular range 
np.random.randint(start,end,no_of_values)

In [50]:
 
c = np.random.randint(6,100,1)
print(c)
arr = np.random.randint(4,20,10)
print(arr)

[25]
[15  9 11  6 15  8  4 17  8 13]


In [55]:
arr = np.random.randint(3,5)
print(arr)
arr = np.random.randint(3,10, size =(3,4))
print(arr)


4
[[8 7 5 3]
 [5 3 9 8]
 [6 6 4 9]]


numpy datatypes and type casting 

In [59]:
arr = np.array([1,2,3,4,6])
print(arr)
arr = np.array([1.2,1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 6]
[1.2 1.  2.  3.  4.  5. ]
<class 'numpy.ndarray'>


In [63]:
list = ["sytr" , 4, 5, None , True ,5.7]
arr = np.array(list)
print(arr)
print(type(arr))
print(arr.dtype)

['sytr' 4 5 None True 5.7]
<class 'numpy.ndarray'>
object


In [69]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
arr = np.array([1.1,3,4,5])
print(arr)
print(arr.dtype)
arr = np.array(['name ',1,2,3])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64
[1.1 3.  4.  5. ]
float64
['name ' '1' '2' '3']
<U21


convert np array from int to float 

In [ ]:
arr = np.array([1,2,3,4,5] , dtype=np.float64)
print(arr)
print(arr.dtype)




[1. 2. 3. 4. 5.]
float64
['1' '2' '3' '4' '5'] <U1


In [74]:

arr = np.array([1,2,3,4,5] , dtype=np.float32)
print(arr)
print(arr.dtype)


[1. 2. 3. 4. 5.]
float32


In [75]:


arr = np.array([1,2,3,4,5], dtype = str)
print(arr , arr.dtype)



['1' '2' '3' '4' '5'] <U1


In [77]:
arr = np.array([1.2,2.2,3.3 ,4.4,5.5], dtype = int)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


convert one datatype to another we do type casting 
for typ casting -> astype()

In [79]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

x = arr.astype(float)
print(x)
print(x.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64


In [80]:
arr = np.array([1.2,3,4,5,])
print(arr)
print(arr.dtype)


x = arr.astype(int)
print(x)
print(x.dtype)


[1.2 3.  4.  5. ]
float64
[1 3 4 5]
int64


## type casting error 
we cannot convert str into int 
we cannot convert str into float

In [108]:
arr = np.array(["name","megha","hello"])
print(arr)
print(arr.dtype)

x = arr.astype(int)
y = arr.astype(float)


['name' 'megha' 'hello']
<U5


ValueError: invalid literal for int() with base 10: np.str_('name')

create multi dimension array
arr.ndim  // no of rows 
arr.shape // rows,columns
arr.size //  no of elemments
arr.itemsize // size of one element in bytes

In [ ]:
arr = np.array([
    [1,2,3],
    [3,4,5] ])
print(arr)


[[1 2 3]
 [3 4 5]]
2
(2, 3)
6
8


In [ ]:
print(arr.ndim)


In [ ]:
print(arr.shape)


In [ ]:
print(arr.size)


In [ ]:
print(arr.itemsize)
## print size of one element in bytes

8


reshaping
to change shape of array without changing the data --> reshape , ravel , flatten

In [ ]:
##reshape 
arr = np.array([1,2,3,4,5,6,7,8])
reshape_array = arr.reshape(4,2)
print(reshape_array)


[[1 2 3 4 5 6 7 8]]


In [ ]:
re1 = reshape_array.reshape(2,4)
print(re1)

[[1 2 3 4]
 [5 6 7 8]]


Ravel for conversion of nd array to one dimension array
multu dimenion array -> 1 d array

no new mwmory created 
faster

change in the ravel array will affect the original array

In [ ]:
print("array is :\n ",re1)

ravvel1 = re1.ravel()
print(" ravel array is : ",ravvel1)
 


array is :
  [[1 2 3 4]
 [5 6 7 8]]
 ravel array is :  [1 2 3 4 5 6 7 8]


In [ ]:
ravvel1[0]=100
print(" after changing ravel array :\n ",ravvel1)


 after changing ravel array :
  [100   2   3   4   5   6   7   8]


In [ ]:
print("after changing ravel array , original array is \n ",re1)

after changing ravel array , original array is 
  [[100   2   3   4]
 [  5   6   7   8]]


flatten 
array -> 1 d array 

new mwmory is created 
slower
changes in flatten array will not affect original array


In [109]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("before flattening \n ",arr)


before flattening 
  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [112]:
arr1 = arr.flatten()
print("after flattening \n ",arr1)

after flattening 
  [1 2 3 4 5 6 7 8 9]


In [113]:
arr1[0]=100
print("after change in flatten array :\n",arr1)
print("after change in flatten array , original array is \n ",arr)


after change in flatten array :
 [100   2   3   4   5   6   7   8   9]
after change in flatten array , original array is 
  [[1 2 3]
 [4 5 6]
 [7 8 9]]


##Arihmatic operations on Arrays

In [115]:
a =np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print("addition of two array : " ,a+b)


addition of two array :  [ 7  9 11 13 15]


In [116]:
a =np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print("subtraction  of two array : " ,a-b)

subtraction  of two array :  [-5 -5 -5 -5 -5]


In [119]:
a =np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(" div  of two array : " , a/b)
print("integer division : ", a//b)


 div  of two array :  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
integer division :  [0 0 0 0 0]


In [118]:
a =np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(" mul  of two array : " ,a*b)

 mul  of two array :  [ 6 14 24 36 50]


In [120]:
a =np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(" modulus   of two array : " ,a%b)

 modulus   of two array :  [1 2 3 4 5]


In [121]:
a =np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(" exponent(power)  of two array : " ,a**2 ,b**2)

 exponent(power)  of two array :  [ 1  4  9 16 25] [ 36  49  64  81 100]


Universal function or ufuncs

In [131]:
## sqrt 
arr = np.array([1,4,9,16,25], dtype=int)
print(arr)
ans = np.sqrt(arr)
print(ans)
print("sqrt of array : ", np.sqrt(arr))

[ 1  4  9 16 25]
[1. 2. 3. 4. 5.]
sqrt of array :  [1. 2. 3. 4. 5.]


In [132]:
##exponential 
# np.exp -> e ^ x , x is integer , array value
arr = np.array([1,2,3,4,5], dtype=int)
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [134]:
##sin func 
## np.sin()

arr = np.array([0,1,2,3,4,5])
print(np.sin(arr))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


indexing with slicing 

In [136]:
a = [1,2,3,4,5,6]
print(a[-1:-4:-1])

[6, 5, 4]


In [137]:
print(a[1::2])

[2, 4, 6]


In [138]:
arr = np.array([10,20,30,40,50,60])
#0 , 2,4 index
print(arr[::2])

[10 30 50]


In [139]:
#negative indexing 
print(arr[-1])

60


In [142]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
# 1st two rows 
print(matrix[:2 , 0:3])

[[1 2 3]
 [4 5 6]]




#index arrays -> advanced  indexing 
pass index to get valus 
# np.take  -> built in func to perform indexing and slicing

In [143]:
arr = np.array([1,2,3,4,5])
ind = [ 0,2,4]
print(np.take(arr,ind))

[1 3 5]


iterating through  nditer()
np.nditer(arr_name)
ndemurator  -> u can fetch both index and value 

In [149]:
arr = np.array([1,2,3,4,5])
for i in np.nditer(arr):
    print(i , end =" ")

1 2 3 4 5 

In [152]:
arr = np.array([1,2,3,4,5])
for ind , x in np.ndenumerate(arr):
    print(ind , x )

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


views vs copies 


In [153]:
arr = np.array([1,2,3,4,5])
view = arr[1:3]
print(view)

[2 3]


In [154]:
view[0] = 100
print(view)
print(arr)

[100   3]
[  1 100   3   4   5]


In [156]:
# copy
arr = np.array([1,2,3,4,5])
copyy = arr[1:3].copy()
print(copyy)



[2 3]


In [157]:
copyy[0]=100
print(copyy)
print(arr)

[100   3]
[1 2 3 4 5]


transpose

In [160]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr.transpose())

[[1 3 5]
 [2 4 6]]
